apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: apr-15-app
  janus-idp.io/tekton: apr-15-app
  backstage.io/kubernetes-id: apr-15-app
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: apr-15-app
resources: 
- deployment.yaml
- route.yaml
- service.yaml
